# Generated by Django 4.2.6 on 2023-10-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='difficulty',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name_category',
            field=models.CharField(max_length=30),
        ),
    ]
