# Generated by Django 4.2.6 on 2023-10-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_alter_categories_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps_cook',
            field=models.TextField(),
        ),
    ]
